# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combotest.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.g1 = QtWidgets.QComboBox(self.centralwidget)
        self.g1.setGeometry(QtCore.QRect(60, 90, 121, 26))
        self.g1.setObjectName("g1")
        self.g2 = QtWidgets.QComboBox(self.centralwidget)
        self.g2.setGeometry(QtCore.QRect(60, 170, 121, 26))
        self.g2.setObjectName("g2")
        self.g3 = QtWidgets.QComboBox(self.centralwidget)
        self.g3.setGeometry(QtCore.QRect(60, 220, 121, 26))
        self.g3.setObjectName("g3")
        self.openbtn = QtWidgets.QPushButton(self.centralwidget)
        self.openbtn.setGeometry(QtCore.QRect(280, 540, 113, 32))
        self.openbtn.setObjectName("openbtn")
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(470, 540, 113, 32))
        self.savebtn.setObjectName("savebtn")
        self.g4 = QtWidgets.QComboBox(self.centralwidget)
        self.g4.setGeometry(QtCore.QRect(60, 270, 121, 26))
        self.g4.setObjectName("g4")
        self.num = QtWidgets.QComboBox(self.centralwidget)
        self.num.setGeometry(QtCore.QRect(60, 130, 61, 26))
        self.num.setObjectName("num")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(180, 90, 111, 21))
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(180, 170, 251, 21))
        self.t2.setObjectName("t2")
        self.t3 = QtWidgets.QLineEdit(self.centralwidget)
        self.t3.setGeometry(QtCore.QRect(180, 270, 251, 21))
        self.t3.setObjectName("t3")
        self.g5 = QtWidgets.QComboBox(self.centralwidget)
        self.g5.setGeometry(QtCore.QRect(60, 350, 121, 26))
        self.g5.setObjectName("g5")
        self.t4 = QtWidgets.QLineEdit(self.centralwidget)
        self.t4.setGeometry(QtCore.QRect(180, 350, 251, 21))
        self.t4.setObjectName("t4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(520, 20, 471, 481))
        self.textEdit.setObjectName("textEdit")
        self.newbtn = QtWidgets.QPushButton(self.centralwidget)
        self.newbtn.setGeometry(QtCore.QRect(660, 540, 113, 32))
        self.newbtn.setObjectName("newbtn")
        self.num1 = QtWidgets.QComboBox(self.centralwidget)
        self.num1.setGeometry(QtCore.QRect(60, 310, 61, 26))
        self.num1.setObjectName("num1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openbtn.setText(_translate("MainWindow", "Open"))
        self.savebtn.setText(_translate("MainWindow", "Save"))
        self.newbtn.setText(_translate("MainWindow", "New"))
